#pragma once
// chat_history.h

#include <vector>
#include <string>
#include <unordered_set>
#include <cstdint>
#include <unordered_map>
#include <utility>

// Poco headers
#include <Poco/JSON/Object.h>

#include "attachment_manager.h"  // for AttachmentInfo
#include "tool_invocation.h"     // for tool_names::kPythonInstallPackage
#include "presented_file.h"      // Presented tool artifact metadata
#include "elision_budget.h"      // self-calibrating elision bytes-per-token
#include "inference_target.h"    // ReasoningDialect (/think wire shape)
#include "context_stats.h"       // RequestBreakdown (context details panel)

// Chat history management class with file persistence
class ChatHistory
{
public:
    ChatHistory();
    ~ChatHistory() = default;

    // Message management
    // model param on assistant messages: tags which model produced the response.
    // Empty string is valid (single-model legacy behavior).
    // target param on user messages: which model was addressed (empty = group turn).
    // attachments: optional metadata about files attached to this message.
    void AddUserMessage(const std::string& content, const std::string& target = "",
                        const std::vector<AttachmentInfo>& attachments = {});
    void AddAssistantMessage(const std::string& content, const std::string& model = "");

    // ── Native function-calling sidecar fields ──────────────────
    //
    // Attach a JSON tool_calls array to the most-recent assistant
    // message.  The array is the verbatim payload received from
    // the structured streaming response (see ChatClient's
    // accumulator) — id/type/function tuples that the next request
    // must thread back as role:"tool" replies via tool_call_id.
    //
    // Stored as a Poco::JSON::Array on the message object so the
    // request builder can serialize it without re-parsing.  No-op
    // if the last message isn't role:"assistant".  toolCallsJson
    // empty → does nothing (preserves the assistant message as
    // pure prose).
    void SetLastAssistantToolCalls(const std::string& toolCallsJson);

    // ── OpenAI Responses sidecar ─────────────────────────────────
    // Attach the verbatim Responses `output` array of an assistant
    // tool-call turn (reasoning items with encrypted_content, message
    // items, function_call items) to the most-recent assistant message
    // under lb_responses::kOutputSidecarKey().  Persists with the
    // conversation like tool_calls.  Projected onto the wire ONLY when
    // the current send target is a Responses endpoint (see
    // SetActiveResponsesApi) and only alongside a surviving tool_calls
    // sidecar; the Responses adapter consumes it to replay the model's
    // own reasoning in front of the function calls it produced.  No-op
    // if the last message isn't role:"assistant" or the JSON is empty.
    void SetLastAssistantResponsesOutput(const std::string& outputJson);

    // ── Generated-images sidecar ─────────────────────────────────
    // Attach chat-folder-relative paths of images generated by an
    // image-output model (e.g. "artifacts/generated_20260709_1.png")
    // to the most-recent assistant message, stored as an "images"
    // string array.  Persists with the conversation like the
    // tool_calls sidecar; ConversationController resolves the paths
    // against the chat folder on replay to redisplay thumbnails.
    // Never emitted on the wire — BuildChatRequestJson only reads
    // role/content/tool sidecars, so history stays cheap to resend.
    // No-op if the last message isn't role:"assistant" or the list
    // is empty.
    void SetLastAssistantImages(const std::vector<std::string>& relPaths);

    // Append a tool-result message that's threaded to a specific
    // assistant tool_call by id.  On the wire (under native
    // protocol) it serializes as role:"tool" with tool_call_id;
    // under XML protocol the id is ignored and the message
    // appears as an ordinary user message.  The content is the
    // existing FormatToolBlockAsUserMessage output so the rendered
    // chat looks identical regardless of protocol.
    //
    // toolCallId empty → falls back to AddUserMessage(content)
    // semantics.  Provided as a single entry point so callers
    // don't need to branch on protocol themselves.
    //
    // toolImages ({absolute path, MIME} pairs, from view_image) are
    // stored on the message as a "tool_images" sidecar.  They are NOT
    // part of `content`; BuildChatRequestJson projects them as
    // image_url parts while the message belongs to the current turn
    // (see the tool-image carrier there).
    void AddToolResultMessage(const std::string& toolCallId,
                              const std::string& content,
                              const std::vector<std::pair<std::string, std::string>>& toolImages = {});

    // Same "tool_images" sidecar for the slash-command path, which
    // persists its tool result through AddUserMessage.  No-op when the
    // list is empty or there is no last message.
    void SetLastMessageToolImages(
        const std::vector<std::pair<std::string, std::string>>& toolImages);

    // History management
    void Clear();
    size_t GetMessageCount() const;
    bool IsEmpty() const;

    // True when the conversation has something worth saving even if it
    // has no chat messages yet: attaching a project to a brand-new chat
    // persists across reloads, and clearing metadata from an
    // already-saved empty chat persists too.
    bool HasPersistableContent() const;

    // ── API integration ───────────────────────────────────────────
    // Build a JSON request body for the OpenAI-compatible /v1/chat/completions endpoint.
    // If systemPrompt is non-empty, it is prepended as a system message.
    // If contextTokens > 0 and the body would exceed ~70% of the token budget
    // (bytes-per-token calibrated from usage reports; see elision_budget.h),
    // old tool-call arguments are shortened and older tool-result bodies are
    // elided, oldest first.  Elided results are spooled to the workspace
    // Vars\ lane and the marker names the file.  The most recent 2 tool
    // results are always preserved intact.
    //
    // When toolsArrayJson is non-empty, it is parsed and attached to the
    // body as the OpenAI function-calling "tools" field.  Empty (the
    // default) means no tools field — the model sees only chat
    // messages.  Build with BuildToolsArrayJson(GetGlobalRouter()) when
    // the active model is on the Native tool protocol.
    //
    // When nativeProtocol is true, stored assistant messages with a
    // "tool_calls" sidecar are emitted as proper assistant tool_call
    // messages (with their content cleared per OpenAI spec), and stored
    // user messages tagged with a "tool_call_id" sidecar are emitted as
    // role:"tool" messages referencing that id.  Dangling tool_calls (an
    // assistant call without a matching tool reply remaining after
    // elision) are dropped to satisfy llama-server's strict request
    // validation.
    //
    // Sampling: local llama-server requests (detected by a .gguf model
    // path) get explicit generation controls instead of server defaults.
    // agentSamplingProfile lowers temperature for tool/builder turns;
    // remote endpoints are left untouched so provider-specific request
    // validators never see llama.cpp-only fields such as top_k/min_p.
    //
    // Not const because the builder must flush the in-memory streaming
    // buffer onto the JSON object before serialization.
    // Poco::SharedPtr propagates const through operator-> (a const
    // SharedPtr yields a const T*), which makes Object::set()
    // uncallable from a const path even though the vector member
    // wouldn't have to be mutated.
    std::string BuildChatRequestJson(const std::string& model, bool stream = true,
                                     const std::string& systemPrompt = "",
                                     int contextTokens = 0,
                                     const std::string& toolsArrayJson = "",
                                     bool nativeProtocol = false,
                                     bool agentSamplingProfile = false,
                                     bool imageOutput = false);

    // ── Context meter support ─────────────────────────────────────
    // Heuristic token estimate for raw text, using the SAME bytes-per-
    // token constant as the elision budget above, so the meter and the
    // elision pass can never disagree by construction.
    static size_t EstimateTokensFromBytes(size_t bytes);

    // The elision threshold (fraction of the context window at which
    // BuildChatRequestJson starts dropping old tool-result bodies).
    // Exposed so the meter's amber state flips at exactly this point.
    static double ElisionBudgetFraction();

    // Raw stored-history bytes (content plus a small per-message
    // overhead); feeds EstimateNextRequestTokens.  O(total content
    // bytes) — call at anchor-invalidation points, not per keystroke.
    size_t EstimateHistoryBytes() const;

    // Number of tool-result bodies elided during the most recent
    // BuildChatRequestJson call.  0 when the last built request fit
    // the budget intact.
    int GetLastBuildElidedCount() const { return m_lastBuildElidedCount; }

    // Number of OLD assistant tool-call turns whose arguments the most
    // recent BuildChatRequestJson shortened (native protocol only).
    // Long PowerShell scripts and write_file bodies the model already
    // ran dominate long agent chats; see tool_call_elision.h.
    // 0 when no turn was shortened.
    int GetLastBuildArgsElidedCount() const { return m_lastBuildArgsElidedCount; }

    // Elision spool: the conversation workspace (tool cwd) whose
    // Vars\ lane receives the full text of tool results that
    // BuildChatRequestJson elides, so the marker can point at a file
    // instead of inviting a rerun.  Empty disables spooling (marker
    // only).  Set before each request build.
    void SetElisionSpoolWorkspace(const std::string& workspaceDirUtf8)
    {
        if (workspaceDirUtf8 != m_elisionSpoolWorkspace) {
            m_elisionSpoolWorkspace = workspaceDirUtf8;
            m_elisionSpoolCache.clear();
        }
    }

    // Byte size of the wire request body produced by the most recent
    // BuildChatRequestJson call.  Paired with the server's reported
    // prompt_tokens (ChatCompletionPayload::PromptTokens) to measure
    // the real bytes-per-token ratio for the running model, instead of
    // assuming the kBytesPerToken constant the heuristic uses.  0 when
    // no request has been built yet on this instance.
    size_t GetLastBuildRequestBytes() const { return m_lastBuildRequestBytes; }

    // Self-calibrating elision budget (elision_budget.h).  Call with the
    // server's exact prompt_tokens for the request most recently built
    // by BuildChatRequestJson (the same pairing the ctx_calibration.tsv
    // logger uses).  Later builds for the same model then size the
    // elision budget from the measured bytes-per-token instead of a
    // fixed 3.0, which can hold a model well below its real window.
    // Implausible or tiny reports are ignored.  The context meter's
    // estimate (EstimateTokensFromBytes) is unaffected.
    void RecordExactPromptTokens(long long promptTokens)
    {
        // A body that elided anything may only lower the ratio (see
        // elision_budget.h: elided bodies measure high and raising on
        // them caused an un-elide/re-elide sawtooth).
        const bool elided = m_lastBuildElidedCount > 0 || m_lastBuildArgsElidedCount > 0;
        m_elisionBpt.Observe(m_lastBuildModel, m_lastBuildRequestBytes, promptTokens, elided);
    }

    // Context meter fallback (no exact usage anchor, e.g. right after a
    // chat is reopened): tokens the NEXT request is expected to occupy.
    // Uses the measured bytes-per-token for `model` when known (seeded
    // from ctx_calibration.tsv on load), else the fixed 3.0, and caps the
    // stored-history bytes at the elision budget the next build will
    // enforce; *wouldElide reports whether that cap applied.  Excludes
    // system prompt and tool schema bytes, so it reads slightly low.
    size_t EstimateNextRequestTokens(const std::string& model, int contextTokens,
                                     bool* wouldElide) const;

    // Model string of the most recent build (what the elision ratio is
    // keyed by).  The calibration log records this, so a seeded ratio is
    // found again by construction.  Empty before the first build.
    const std::string& GetLastBuildModel() const { return m_lastBuildModel; }

    // Bytes-per-token the next build for `model` will budget elision with.
    double GetElisionBytesPerToken(const std::string& model) const
    {
        return m_elisionBpt.Current(model);
    }

    // What the most recent BuildChatRequestJson body was made of
    // (system prompt, tool definitions, messages by role, images).
    // Feeds the context details panel.  Empty before the first build.
    const RequestBreakdown& GetLastBuildBreakdown() const { return m_lastBuildBreakdown; }

    // True when the most recent BuildChatRequestJson emitted a
    // multimodal content array for the image-carrier user message.
    // Read by the send path to skip the AttachmentManager::
    // InjectImagesIntoRequest fallback, whose only remaining job on a
    // projected body is to Poco-parse the entire request (multi-MB
    // once base64 data URIs are aboard) and discover the content is
    // already structured.  False when projection could not run
    // (unsaved conversation → no chat dir, or attachment rows without
    // a persisted storage_path) — in those cases the injector is still
    // the only way images reach the wire.
    bool LastBuildProjectedImages() const { return m_lastBuildProjectedImages; }

    // ── Streaming support methods ─────────────────────────────────
    void AddAssistantPlaceholder(const std::string& model = "");
    void AppendToLastAssistantMessage(const std::string& delta);
    void UpdateLastAssistantMessage(const std::string& content);
    void RemoveLastAssistantMessage();
    bool HasAssistantPlaceholder() const;

    // ── Access methods ────────────────────────────────────────────
    const std::vector<Poco::JSON::Object::Ptr>& GetMessages() const;

    // Read the "model" field from a message (empty string if absent)
    static std::string GetMessageModel(const Poco::JSON::Object::Ptr& msg);

    // Read the "target" field from a user message (empty string if absent/group turn)
    static std::string GetMessageTarget(const Poco::JSON::Object::Ptr& msg);

    // Utility methods
    std::string GetLastAssistantMessage() const;

    // ── File persistence ─────────────────────────────────────────

    // Immutable, thread-safe persistence snapshot.  CreateSaveSnapshot runs
    // briefly on the UI thread to copy current state into plain STL values;
    // WriteSaveSnapshot performs JSON construction, stringify, staged file
    // I/O, and rename on a background persistence worker.
    struct SaveMessageSnapshot {
        std::string role;
        std::string content;
        std::string model;
        std::string target;
        std::string toolCallId;
        std::string attachmentsJson;
        std::string toolCallsJson;
        std::string imagesJson;
        std::string toolImagesJson;
        std::string responsesOutputJson;
    };

    // ── Per-conversation reasoning override (/think) ─────────────
    // Auto sends nothing on the wire, preserving the historical
    // request shape.  Everything else asks the backend to enable or
    // suppress model reasoning, expressed per target:
    //
    //   * Local llama-server (.gguf model value):
    //     chat_template_kwargs.enable_thinking — a boolean, honored by
    //     hybrid-reasoning chat templates such as Qwen3 under --jinja
    //     and ignored by templates that never reference it.  Templates
    //     have no effort vocabulary, so Low/Medium/High all enable.
    //   * Remote, OpenRouter dialect: a "reasoning" object —
    //     {"enabled": bool} for On/Off (the historical shape),
    //     {"effort": "low|medium|high"} for the effort levels.
    //   * Remote, OpenAI dialect (direct api.openai.com):
    //     "reasoning_effort" string — Off -> "none" (which also
    //     unblocks function tools on models whose server-side default
    //     effort conflicts with tools), On -> "medium" (the provider
    //     default when reasoning is enabled), levels map 1:1.
    //
    // Which remote dialect applies comes from the resolved
    // InferenceTarget via SetActiveReasoningDialect below.
    enum class ThinkOverride { Auto, On, Off, Low, Medium, High };

    struct SaveSnapshot {
        std::string filePath;
        std::string title;
        std::string createdAt;
        std::string updatedAt;
        std::string toolCwd;
        unsigned long toolTimeoutMs = 0;
        ThinkOverride thinkOverride = ThinkOverride::Auto;
        std::string projectId;
        std::string projectName;
        std::string projectRoot;
        bool pinned = false;
        bool archived = false;
        std::string modelSelection;
        std::vector<std::string> models;
        std::vector<SaveMessageSnapshot> messages;
        std::string titleMarkerPath;
        std::uint64_t revision = 0;
    };

    bool CreateSaveSnapshot(const std::string& filePath,
                            const std::vector<std::string>& models,
                            SaveSnapshot& outSnapshot,
                            bool touchActivityTimestamp = true);
    static bool WriteSaveSnapshot(const SaveSnapshot& snapshot,
                                  bool durable = false);
    void CommitSaveSnapshot(const SaveSnapshot& snapshot);
    std::uint64_t GetRevision() const { return m_revision; }

    // Save conversation to a JSON file. If filePath is empty, uses m_filePath.
    // models: list of models used (single-element for normal chat, two for group).
    //
    // durable (default true): when true, force the staged temp's bytes to
    // stable storage (FlushFileBuffers) and commit the rename with
    // MOVEFILE_WRITE_THROUGH.  Routine per-turn autosaves pass false: the
    // staged-temp + atomic-rename pattern ALONE already guarantees the
    // on-disk file is either the previous save or the new one against any
    // app crash — the two synchronous storage flushes only add protection
    // against sudden power loss / OS crash within the OS write-back window
    // (a few seconds), at the cost of a UI-thread stall at the end of
    // every turn.  Non-durable saves simply revert to the previous
    // autosave in that rare scenario.  Keep durable=true wherever the
    // in-memory history is about to be cleared or replaced (close, New
    // Chat, conversation switch, model/folder change) — at those points
    // the file becomes the only copy.
    // touchActivityTimestamp permits updated_at to advance only when new
    // message activity is pending. Clean/manual/durable saves preserve it.
    // Normal content saves leave this true. Sidebar-only metadata operations such as
    // rename, pin, archive, and project reassignment pass false so the chat's
    // displayed age and chronological position remain tied to message activity.
    bool SaveToFile(const std::string& filePath, const std::vector<std::string>& models,
                    bool durable = true,
                    bool touchActivityTimestamp = true);
    // Convenience overload for single-model save (wraps into vector).
    bool SaveToFile(const std::string& filePath, const std::string& model,
                    bool durable = true,
                    bool touchActivityTimestamp = true);

    // Load conversation from a JSON file.
    // outModels: populated with the model(s) stored in the file.
    bool LoadFromFile(const std::string& filePath, std::vector<std::string>& outModels);
    // Convenience overload: returns first model only (backwards compat).
    bool LoadFromFile(const std::string& filePath, std::string& outModel);

    // File path management
    std::string GetFilePath() const { return m_filePath; }
    void SetFilePath(const std::string& path) { m_filePath = path; }
    bool HasFilePath() const { return !m_filePath.empty(); }

    // Dirty tracking — true when content has changed since last save/load
    bool IsDirty() const { return m_dirty; }

    // Drop-import contract: a dropped file has been copied into this
    // conversation's Workspace folder.  That copy is durable,
    // user-visible on-disk state even though no message was added, so
    // the conversation must persist — otherwise the freshly minted
    // chat folder (EnsureConversationChatFolder) is orphaned: no JSON
    // is written, the chat never appears in the sidebar, and the
    // DeleteConversation cleanup that removes chat folders is
    // unreachable forever.  Marking dirty lets AutoSaveConversation
    // write the JSON and keeps the existing cleanup path in play.
    void NoteWorkspaceSideEffect() { MarkDirty(); }

    // Conversation metadata
    std::string GetTitle() const { return m_title; }
    void SetTitle(const std::string& title) {
        if (title != m_title) {
            m_title = title;
            MarkDirty();
        }
    }
    std::string GetCreatedAt() const { return m_createdAt; }

    // Sidebar organization metadata.  Omitted from legacy conversation
    // files when false, so older builds continue to load the chat body.
    bool IsPinned() const { return m_pinned; }
    void SetPinned(bool pinned) {
        if (pinned != m_pinned) {
            m_pinned = pinned;
            MarkDirty();
        }
    }
    bool IsArchived() const { return m_archived; }
    void SetArchived(bool archived) {
        if (archived != m_archived) {
            m_archived = archived;
            MarkDirty();
        }
    }

    // Exact model selection this conversation was using, persisted as
    // "model_selection" next to "models".  For remote models this is the
    // "remote:<endpoint>/<model>" key, so reopening the chat returns to the
    // same connection even when several connections offer the same model
    // id.  Empty for local models and for files written by older builds.
    // Stamped by ConversationController before each save; like "models",
    // changing it does not by itself mark the history dirty.
    const std::string& GetModelSelection() const { return m_modelSelection; }
    void SetModelSelection(const std::string& key) { m_modelSelection = key; }

    // ── Project association ──────────────────────────────────────
    // Optional long-lived project attached to this conversation.  A
    // missing project keeps plain chat behavior.  Project folders are
    // never deleted when a chat is deleted; they are durable user data.
    bool HasProject() const { return !m_projectId.empty() && !m_projectRoot.empty(); }
    std::string GetProjectId() const { return m_projectId; }
    std::string GetProjectName() const { return m_projectName; }
    std::string GetProjectRoot() const { return m_projectRoot; }
    void SetProject(const std::string& id,
                    const std::string& name,
                    const std::string& root) {
        if (id != m_projectId || name != m_projectName || root != m_projectRoot) {
            m_projectId = id;
            m_projectName = name;
            m_projectRoot = root;
            MarkDirty();
        }
    }
    void ClearProject() {
        if (HasProject() || !m_projectName.empty()) {
            m_projectId.clear();
            m_projectName.clear();
            m_projectRoot.clear();
            MarkDirty();
        }
    }

    // ── Tool execution context ────────────────────────────────────
    // Per-conversation working directory override set by /cd.  Empty
    // string means "use the conversation workspace".  Persisted
    // alongside the conversation so switching chats restores the right
    // context.
    std::string GetToolCwd() const { return m_toolCwd; }
    void        SetToolCwd(const std::string& cwd) {
        if (cwd != m_toolCwd) {
            m_toolCwd = cwd;
            MarkDirty();
        }
    }

    // Per-conversation timeout override for tool execution, in
    // milliseconds.  0 means "use the global default"
    // (kDefaultToolTimeoutMs in tool_context.h).  Kept on ChatHistory
    // so agent-harness conversations can carry their own limits.
    unsigned long GetToolTimeoutMs() const { return m_toolTimeoutMs; }
    void          SetToolTimeoutMs(unsigned long ms) {
        if (ms != m_toolTimeoutMs) {
            m_toolTimeoutMs = ms;
            MarkDirty();
        }
    }

    // Per-conversation reasoning override
    // (/think on|off|auto|low|medium|high).  Persisted alongside the
    // conversation like the tool CWD so switching chats restores the
    // chosen mode.
    ThinkOverride GetThinkOverride() const { return m_thinkOverride; }
    void          SetThinkOverride(ThinkOverride mode) {
        if (mode != m_thinkOverride) {
            m_thinkOverride = mode;
            MarkDirty();
        }
    }

    // Reasoning dialect of the conversation's CURRENT send target.
    // Transient, deliberately NOT persisted and NOT MarkDirty'd: the
    // frame sets it from the resolved InferenceTarget at the start of
    // every turn (and again in the agent sendRequest seam), so a
    // conversation moved between endpoints always builds with the
    // dialect of the target it is actually about to hit.  Read by
    // BuildChatRequestJson when /think is not auto and the model is
    // remote.  Defaults to the historical OpenRouter-style object.
    void SetActiveReasoningDialect(ReasoningDialect d) {
        m_reasoningDialect = d;
    }

    // Whether the conversation's CURRENT send target is an OpenAI
    // Responses endpoint.  Same lifetime and discipline as the dialect
    // above: transient, set by the frame from the resolved target at
    // turn start and in the agent sendRequest seam.  Gates projection
    // of the Responses output sidecar so a Chat Completions provider
    // never receives a message key it does not know.
    void SetActiveResponsesApi(bool on) { m_responsesApi = on; }

    // Per-conversation approval memory.  In this polish pass, plain
    // approve enables one-approval mode for this chat; approve once
    // remains available for a single-card approval.  After trust is
    // enabled, subsequent approval-required tools skip the approval
    // card until the conversation is cleared or reloaded.
    //
    // Exception: python_install_package is intentionally excluded from
    // the chat-wide trust flag.  Each install names a distinct package
    // that touches the user's Python environment, so it always renders
    // its own approval card with the exact package name even when
    // one-approval mode is on.  An explicit "approve once" of an
    // install request still individually remembers that single tool
    // name (via RememberToolApproval), but installs cannot be
    // wholesale-approved for the rest of the chat.
    //
    // This flag itself is in-memory only and is never persisted with
    // the conversation file.  However, trust now has app-SESSION
    // lifetime rather than dying on every reload: granting chat-wide
    // trust also records the conversation path in
    // ConversationRegistry (RememberSessionTrust), and
    // ConversationController::LoadConversationFromPath re-arms this
    // flag when a session-trusted conversation is reopened.  Restarting
    // LlamaBoss clears all session grants, so a conversation reopened
    // in a later run always starts with a clean trust state.
    bool IsToolChatApproved(const std::string& name) const {
        if (name == tool_names::kPythonInstallPackage) {
            // Per-package review is the safety boundary now that the
            // package allowlist has been retired.  Never bypass.
            return false;
        }
        return m_chatApprovalTrustEnabled ||
               (!name.empty() && m_chatApprovedTools.count(name) > 0);
    }
    bool IsChatApprovalTrustEnabled() const {
        return m_chatApprovalTrustEnabled;
    }
    void RememberToolApproval(const std::string& name) {
        if (!name.empty()) m_chatApprovedTools.insert(name);
    }
    void RememberAllToolApprovalsForChat() {
        m_chatApprovalTrustEnabled = true;
    }
    void ClearChatApprovedTools() {
        m_chatApprovedTools.clear();
        m_chatApprovalTrustEnabled = false;
    }

    // Session-only native write capabilities granted from the folder-access
    // card.  They are intentionally not serialized: reopening LlamaBoss
    // starts with a clean filesystem trust boundary.  The exact canonical
    // roots are copied into every ToolContext, so write/edit/mkdir/delete and
    // their slash-command forms all see the same authorization set.
    const std::vector<std::string>& GetChatWriteRoots() const {
        return m_chatWriteRoots;
    }
    bool GrantWriteRootForChat(const std::string& canonicalRoot);
    void ClearChatWriteRoots() { m_chatWriteRoots.clear(); }

    // Generate a title from the first user message
    std::string GenerateTitle() const;
    // Same rules as GenerateTitle, for a single piece of user text
    // ("" when it yields nothing usable).
    static std::string TitleFromUserText(const std::string& text);
    // Title used to name this chat's folder: the explicit title when set,
    // else the generated one.
    std::string GetChatFolderTitle() const;

    // Get the default conversations directory (creates it if needed)
    static std::string GetConversationsDir();
    // Generate a unique filename for a new conversation
    static std::string GenerateFilePath();

    // ── Per-conversation chat folders ─────────────────────────────
    // User-visible working area for files created/imported during a
    // single conversation.  Conversation JSON stays under
    // %LOCALAPPDATA%\LlamaBoss\conversations; chat files live under
    //   %USERPROFILE%\LlamaBoss\Chats\<date>_<title-slug>_<id>
    // e.g. Chats\2026-09-26_invoice-parser-fix_1ed3d3c2.  Naming and
    // recognition rules live in chat_folders.h.
    //
    // The folder is found by the id in the conversation filename, never by
    // title, and is named once at creation (renaming a chat does not rename
    // its folder).  Folders left in the legacy LlamaBoss\Workflows root are
    // still found.
    //
    // This keeps each chat's files together, lets new chats reuse clean
    // filenames, and makes deleting a chat able to delete its files too.
    static std::string GetChatsRootDir();          // ...\LlamaBoss\Chats (created)
    static std::string GetLegacyChatsRootDir();    // ...\LlamaBoss\Workflows (never created)
    static std::string GetChatFolder(const std::string& conversationPath);
    static std::string GetConversationWorkspaceDir(const std::string& conversationPath);
    // Creates the chat folder if needed.  `title` only matters the first
    // time (it becomes the folder's slug); pass GetChatFolderTitle() or,
    // before the first message is recorded, TitleFromUserText(input).
    static bool        EnsureChatFolder(const std::string& conversationPath,
                                        const std::string& title = std::string());
    // Drop the cached folder for a deleted conversation.
    static void        ForgetChatFolder(const std::string& conversationPath);
    // Rewrites an absolute path inside a legacy Workflows\chat_<id> folder
    // to that chat's migrated folder.  Returns `path` unchanged otherwise.
    static std::string RemapLegacyChatPath(const std::string& path);

    // One-time startup move of LlamaBoss\Workflows\chat_<id> folders into
    // LlamaBoss\Chats\<date>_<slug>_<id>.  Safe to call every launch: it is
    // a no-op once the legacy root is gone.  Folders that cannot be moved
    // (file in use) stay where they are and keep working.
    struct ChatFolderMigrationResult {
        int moved = 0;
        int skipped = 0;   // destination already existed
        int failed = 0;
        std::vector<std::string> failedFolders;
    };
    static ChatFolderMigrationResult MigrateLegacyChatFolders();

    // ── Attachment sidecar helpers ────────────────────────────────
    // User-uploaded attachments live inside the conversation chat
    // folder.
    static std::string GetAttachmentDir(const std::string& conversationPath);

    // Relative path prefix stored in message attachment metadata.  This
    // remains relative for history portability, but is now relative to
    // the chat folder root.
    static std::string GetAttachmentRelDir(const std::string& conversationPath);

    // ── Generated-files sidecar helpers ───────────────────────────
    // Files generated from assistant code blocks/artifacts.
    static std::string GetGeneratedFilesDir(const std::string& conversationPath);
    static std::string GetGeneratedFilesRelDir(const std::string& conversationPath);

    // ── Tool-result formatting ────────────────────────────────────
    // Unified formatter for any tool invocation round-tripped into the
    // conversation history as a user message.  Emits:
    //
    //   [tool: <toolTag>]
    //   > <commandEcho>
    //
    //   ```<bodyLang>
    //   <body>
    //   ```
    //
    //   [error]
    //   ```
    //   <errorBody>
    //   ```
    //
    //   [status: <chip1>, <chip2>, ...]
    //
    // The body fence length is computed as N+1 backticks where N is
    // the longest backtick run in the body — this keeps the fence
    // robust when a read dumps a markdown file or a code sample that
    // itself contains ``` fences.  Error body uses the same rule.
    // Any section whose input string is empty is skipped; an empty
    // body is common for "did nothing useful" commands like
    // `$null = 1+1`.
    static std::string FormatToolBlockAsUserMessage(
        const std::string& toolTag,
        const std::string& commandEcho,
        const std::string& body,
        const std::string& errorBody,
        const std::vector<std::string>& statusChips,
        const std::string& bodyLang = "",
        const std::vector<PresentedFile>& presentedFiles = {});

private:
    std::vector<Poco::JSON::Object::Ptr> m_messages;

    // Tool-result bodies elided by the most recent BuildChatRequestJson
    // call (context meter's "·elided" indicator).  Reset at the start of
    // every build.
    int m_lastBuildElidedCount = 0;

    // Assistant tool-call turns whose arguments were shortened by the
    // most recent build.  Reset at the start of every build.
    int m_lastBuildArgsElidedCount = 0;

    // Elision spool target and content-hash -> Vars\ path cache (skips
    // the filesystem check on every build once a result is spooled).
    std::string m_elisionSpoolWorkspace;
    std::unordered_map<uint64_t, std::string> m_elisionSpoolCache;

    // Byte size of the body returned by the most recent
    // BuildChatRequestJson call.  Set at the single return point, so it
    // always describes the FINAL body (post-elision, post-sanitizer).
    size_t m_lastBuildRequestBytes = 0;

    // Model of the most recent build (pairs the measured bytes with the
    // model that produced prompt_tokens) and the learned elision ratio.
    std::string m_lastBuildModel;
    lb_elision::AdaptiveBytesPerToken m_elisionBpt;

    // Replays <chat folder>\ctx_calibration.tsv into m_elisionBpt (load).
    void SeedElisionCalibrationFromChatFolder();

    // Per-section sizes of that same final body (context details panel).
    RequestBreakdown m_lastBuildBreakdown;

    // Whether the most recent BuildChatRequestJson projected persisted
    // image attachments into a multimodal content array (image
    // carrier).  Reset at the start of every build and of every
    // stringify pass, so the value always reflects the FINAL body.
    bool m_lastBuildProjectedImages = false;

    // File persistence state
    std::string m_filePath;     // Current file path (empty = unsaved)
    std::string m_title;        // Conversation title
    std::string m_createdAt;    // ISO timestamp of creation
    std::string m_updatedAt;    // ISO timestamp of last content activity
    bool        m_dirty = false; // True when content changed since last save/load
    bool        m_contentActivityPending = false; // Message changes, not metadata/save activity
    std::uint64_t m_revision = 0; // Monotonic mutation generation for async save commits

    void MarkDirty(bool contentActivity = false) {
        m_dirty = true;
        m_contentActivityPending = m_contentActivityPending || contentActivity;
        ++m_revision;
    }

    // Tool execution context — persisted per-conversation.
    // Empty / 0 means "use the default" at resolution time.
    std::string   m_toolCwd;
    unsigned long m_toolTimeoutMs = 0;

    // Per-conversation reasoning override (/think).  Auto keeps the
    // historical request shape (no reasoning fields on the wire).
    ThinkOverride m_thinkOverride = ThinkOverride::Auto;

    // Dialect of the current send target (see SetActiveReasoningDialect).
    ReasoningDialect m_reasoningDialect = ReasoningDialect::OpenRouterStyle;

    // Current send target is a Responses endpoint (see SetActiveResponsesApi).
    bool m_responsesApi = false;

    // Optional project association.
    std::string m_projectId;
    std::string m_projectName;
    std::string m_projectRoot;

    // Sidebar organization metadata.
    bool m_pinned = false;
    bool m_archived = false;

    // See GetModelSelection().
    std::string m_modelSelection;

    // Per-conversation approval memory (in-memory only; cleared on
    // Clear() and on conversation load).  Lives here rather than on
    // the agent or frame so loading a different chat naturally drops
    // the prior session's approval choices.
    bool m_chatApprovalTrustEnabled = false;
    std::unordered_set<std::string> m_chatApprovedTools;

    // In-memory only.  Never persisted to conversation JSON.
    std::vector<std::string> m_chatWriteRoots;

    // Streaming accumulation buffer — avoids O(n²) string concatenation
    // in AppendToLastAssistantMessage by accumulating here instead of
    // repeatedly reading/writing the Poco JSON object per delta.
    //
    // The Poco JSON object's "content" field is the source of truth on disk
    // and on the wire; m_streamBuffer is the source of truth in memory while
    // a response is streaming.  The two are reconciled lazily by
    // FlushStreamBuffer() — called automatically before any reader (Save,
    // BuildChatRequestJson) and on stream completion via
    // UpdateLastAssistantMessage().  Syncing only after enough bytes have
    // accumulated amortizes the cost; per-delta sync would make streaming
    // O(n²) in body bytes.
    //
    // m_streamBufferDirty is the byte count buffered since the last sync to
    // the JSON object.  It only ticks under non-const flush paths, so it
    // does not need to be mutable; FlushStreamBuffer() is non-const because
    // Poco::SharedPtr propagates const through operator-> (a const
    // SharedPtr yields a const T*), preventing Object::set() from a const
    // member.  See FlushStreamBuffer() for the matching rationale.
    std::string m_streamBuffer;
    std::size_t m_streamBufferDirty = 0;

    // Helper methods
    Poco::JSON::Object::Ptr CreateMessage(const std::string& role,
                                          const std::string& content,
                                          const std::string& model = "");
    bool IsLastMessageRole(const std::string& role) const;
    static std::string CurrentTimestamp();

    // Sync the in-memory streaming buffer onto the last assistant message's
    // JSON "content" field.  No-op if the buffer is clean or the last
    // message is not an assistant message.  See m_streamBuffer comment for
    // the full lifetime / consistency contract.
    //
    // Not const: Poco::SharedPtr's operator->() const returns a const T*,
    // so calling Object::set() through m_messages.back() requires non-const
    // access even though the vector itself is not modified.  Callers that
    // need to flush from an otherwise-const reader path should drop const
    // on themselves rather than reach for const_cast here.
    void FlushStreamBuffer();
};
