#pragma once
// chat_history.h

#include <vector>
#include <string>
#include <unordered_set>
#include <cstdint>

// Poco headers
#include <Poco/JSON/Object.h>

#include "attachment_manager.h"  // for AttachmentInfo
#include "tool_invocation.h"     // for tool_names::kPythonInstallPackage
#include "goal_state.h"          // Goals Phase 1: per-conversation in-memory goal state
#include "presented_file.h"      // Presented tool artifact metadata

// Chat history management class with file persistence
class ChatHistory
{
public:
    ChatHistory();
    ~ChatHistory() = default;

    // Message management
    // model param on assistant messages: tags which model produced the response.
    // Empty string is valid (single-model legacy behavior).
    // target param on user messages: which model was addressed (empty = group turn).
    // attachments: optional metadata about files attached to this message.
    void AddUserMessage(const std::string& content, const std::string& target = "",
                        const std::vector<AttachmentInfo>& attachments = {});
    void AddAssistantMessage(const std::string& content, const std::string& model = "");
    void AddSystemMessage(const std::string& content);

    // ── Phase 3c-ii: native function-calling sidecar fields ─────
    //
    // Attach a JSON tool_calls array to the most-recent assistant
    // message.  The array is the verbatim payload received from
    // llama-server's structured streaming response (see
    // ChatClient's accumulator in Phase 3c-ii) — id/type/function
    // tuples that the next request must thread back as role:"tool"
    // replies via tool_call_id.
    //
    // Stored as a Poco::JSON::Array on the message object so the
    // request builder can serialize it without re-parsing.  No-op
    // if the last message isn't role:"assistant".  toolCallsJson
    // empty → does nothing (preserves the assistant message as
    // pure prose).
    void SetLastAssistantToolCalls(const std::string& toolCallsJson);

    // ── Generated-images sidecar ─────────────────────────────────
    // Attach workflow-relative paths of images generated by an
    // image-output model (e.g. "artifacts/generated_20260709_1.png")
    // to the most-recent assistant message, stored as an "images"
    // string array.  Persists with the conversation like the
    // tool_calls sidecar; ConversationController resolves the paths
    // against the workflow folder on replay to redisplay thumbnails.
    // Never emitted on the wire — BuildChatRequestJson only reads
    // role/content/tool sidecars, so history stays cheap to resend.
    // No-op if the last message isn't role:"assistant" or the list
    // is empty.
    void SetLastAssistantImages(const std::vector<std::string>& relPaths);

    // Append a tool-result message that's threaded to a specific
    // assistant tool_call by id.  On the wire (under native
    // protocol) it serializes as role:"tool" with tool_call_id;
    // under XML protocol the id is ignored and the message
    // appears as an ordinary user message.  The content is the
    // existing FormatToolBlockAsUserMessage output so the rendered
    // chat looks identical regardless of protocol.
    //
    // toolCallId empty → falls back to AddUserMessage(content)
    // semantics.  Provided as a single entry point so callers
    // don't need to branch on protocol themselves.
    void AddToolResultMessage(const std::string& toolCallId,
                              const std::string& content);

    // History management
    void Clear();
    size_t GetMessageCount() const;
    bool IsEmpty() const;

    // True when the conversation has something worth saving even if it
    // has no chat messages yet.  Projects Phase 1 uses this so attaching
    // a project to a brand-new chat can persist across reloads, and so
    // clearing metadata from an already-saved empty chat can persist too.
    bool HasPersistableContent() const;

    // ── API integration ───────────────────────────────────────────
    // Build a JSON request body for the OpenAI-compatible /v1/chat/completions endpoint.
    // If systemPrompt is non-empty, it is prepended as a system message.
    // If contextTokens > 0 and the body would exceed ~70% of the token budget
    // (estimated at 3 bytes/token), older tool-result bodies are elided with
    // a replay hint so the model can re-issue the call if it needs the data.
    // The most recent 2 tool results are always preserved intact.
    //
    // Phase 3c-i: when toolsArrayJson is non-empty, it is parsed and
    // attached to the body as the OpenAI function-calling "tools"
    // field.  Empty (the default) preserves Phase 1/2 behavior — no
    // tools field, the model sees only chat messages.  Build with
    // BuildToolsArrayJson(GetGlobalRouter()) when the active model
    // is on the Native tool protocol.
    //
    // Phase 3c-ii: when nativeProtocol is true, stored assistant
    // messages with a "tool_calls" sidecar are emitted as proper
    // assistant tool_call messages (with their content cleared per
    // OpenAI spec), and stored user messages tagged with a
    // "tool_call_id" sidecar are emitted as role:"tool" messages
    // referencing that id.  Dangling tool_calls (an assistant call
    // without a matching tool reply remaining after elision) are
    // dropped to satisfy llama-server's strict request validation.
    //
    // Sampling: local llama-server requests (detected by a .gguf model
    // path) get explicit generation controls instead of server defaults.
    // agentSamplingProfile lowers temperature for tool/goal/builder turns;
    // remote endpoints are left untouched so provider-specific request
    // validators never see llama.cpp-only fields such as top_k/min_p.
    //
    // Not const because the builder must flush the in-memory streaming
    // buffer onto the JSON object before serialization.
    // Poco::SharedPtr propagates const through operator-> (a const
    // SharedPtr yields a const T*), which makes Object::set()
    // uncallable from a const path even though the vector member
    // wouldn't have to be mutated.
    std::string BuildChatRequestJson(const std::string& model, bool stream = true,
                                     const std::string& systemPrompt = "",
                                     int contextTokens = 0,
                                     const std::string& toolsArrayJson = "",
                                     bool nativeProtocol = false,
                                     bool agentSamplingProfile = false,
                                     bool imageOutput = false);

    // ── Context meter support ─────────────────────────────────────
    // Heuristic token estimate for raw text, using the SAME bytes-per-
    // token constant as the elision budget above, so the meter and the
    // elision pass can never disagree by construction.
    static size_t EstimateTokensFromBytes(size_t bytes);

    // The elision threshold (fraction of the context window at which
    // BuildChatRequestJson starts dropping old tool-result bodies).
    // Exposed so the meter's amber state flips at exactly this point.
    static double ElisionBudgetFraction();

    // Rough token estimate for the full stored history (content bytes
    // plus a small per-message overhead).  Used as the meter's fallback
    // anchor after a conversation load, before the first exact usage
    // report arrives from the server.  O(total content bytes) — call at
    // anchor-invalidation points, not per keystroke.
    size_t EstimateHistoryTokens() const;

    // Number of tool-result bodies elided during the most recent
    // BuildChatRequestJson call.  0 when the last built request fit
    // the budget intact.
    int GetLastBuildElidedCount() const { return m_lastBuildElidedCount; }

    // True when the most recent BuildChatRequestJson emitted a
    // multimodal content array for the image-carrier user message
    // (Phase 1c projection).  Read by the send path to skip the
    // legacy AttachmentManager::InjectImagesIntoRequest fallback,
    // whose only remaining job on a projected body is to Poco-parse
    // the entire request (multi-MB once base64 data URIs are aboard)
    // and discover the content is already structured.  False when
    // projection could not run (unsaved conversation → no workflow
    // dir, or attachment rows without a persisted storage_path) —
    // in those cases the injector is still the only way images
    // reach the wire.
    bool LastBuildProjectedImages() const { return m_lastBuildProjectedImages; }

    // ── Streaming support methods ─────────────────────────────────
    void AddAssistantPlaceholder(const std::string& model = "");
    void AppendToLastAssistantMessage(const std::string& delta);
    void UpdateLastAssistantMessage(const std::string& content);
    void RemoveLastAssistantMessage();
    void RemoveLastSystemMessage();
    bool HasAssistantPlaceholder() const;

    // ── Access methods ────────────────────────────────────────────
    const std::vector<Poco::JSON::Object::Ptr>& GetMessages() const;

    // Read the "model" field from a message (empty string if absent)
    static std::string GetMessageModel(const Poco::JSON::Object::Ptr& msg);

    // Read the "target" field from a user message (empty string if absent/group turn)
    static std::string GetMessageTarget(const Poco::JSON::Object::Ptr& msg);

    // Utility methods
    std::string GetLastUserMessage() const;
    std::string GetLastAssistantMessage() const;

    // ── File persistence ─────────────────────────────────────────

    // Immutable, thread-safe persistence snapshot.  CreateSaveSnapshot runs
    // briefly on the UI thread to copy current state into plain STL values;
    // WriteSaveSnapshot performs JSON construction, stringify, staged file
    // I/O, and rename on a background persistence worker.
    struct SaveMessageSnapshot {
        std::string role;
        std::string content;
        std::string model;
        std::string target;
        std::string toolCallId;
        std::string attachmentsJson;
        std::string toolCallsJson;
        std::string imagesJson;
    };

    // ── Per-conversation reasoning override (/think) ─────────────
    // Auto sends nothing on the wire, preserving the historical
    // request shape.  On/Off ask the backend to enable or suppress
    // model reasoning: local llama-server targets receive
    // chat_template_kwargs.enable_thinking (honored by
    // hybrid-reasoning chat templates such as Qwen3 under --jinja;
    // templates that never reference the flag ignore it), remote
    // OpenAI-compatible targets receive an OpenRouter-style
    // reasoning object.
    enum class ThinkOverride { Auto, On, Off };

    struct SaveSnapshot {
        std::string filePath;
        std::string title;
        std::string createdAt;
        std::string updatedAt;
        std::string toolCwd;
        unsigned long toolTimeoutMs = 0;
        ThinkOverride thinkOverride = ThinkOverride::Auto;
        std::string projectId;
        std::string projectName;
        std::string projectRoot;
        bool pinned = false;
        bool archived = false;
        GoalState goalState;
        std::vector<std::string> models;
        std::vector<SaveMessageSnapshot> messages;
        std::string titleMarkerPath;
        std::uint64_t revision = 0;
    };

    bool CreateSaveSnapshot(const std::string& filePath,
                            const std::vector<std::string>& models,
                            SaveSnapshot& outSnapshot,
                            bool touchActivityTimestamp = true);
    static bool WriteSaveSnapshot(const SaveSnapshot& snapshot,
                                  bool durable = false);
    void CommitSaveSnapshot(const SaveSnapshot& snapshot);
    std::uint64_t GetRevision() const { return m_revision; }

    // Save conversation to a JSON file. If filePath is empty, uses m_filePath.
    // models: list of models used (single-element for normal chat, two for group).
    //
    // durable (default true): when true, force the staged temp's bytes to
    // stable storage (FlushFileBuffers) and commit the rename with
    // MOVEFILE_WRITE_THROUGH.  Routine per-turn autosaves pass false: the
    // staged-temp + atomic-rename pattern ALONE already guarantees the
    // on-disk file is either the previous save or the new one against any
    // app crash — the two synchronous storage flushes only add protection
    // against sudden power loss / OS crash within the OS write-back window
    // (a few seconds), at the cost of a UI-thread stall at the end of
    // every turn.  Non-durable saves simply revert to the previous
    // autosave in that rare scenario.  Keep durable=true wherever the
    // in-memory history is about to be cleared or replaced (close, New
    // Chat, conversation switch, model/folder change) — at those points
    // the file becomes the only copy.
    // touchActivityTimestamp controls whether updated_at advances. Normal
    // content saves leave this true. Sidebar-only metadata operations such as
    // rename, pin, archive, and project reassignment pass false so the chat's
    // displayed age and chronological position remain tied to message activity.
    bool SaveToFile(const std::string& filePath, const std::vector<std::string>& models,
                    bool durable = true,
                    bool touchActivityTimestamp = true);
    // Convenience overload for single-model save (wraps into vector).
    bool SaveToFile(const std::string& filePath, const std::string& model,
                    bool durable = true,
                    bool touchActivityTimestamp = true);

    // Load conversation from a JSON file.
    // outModels: populated with the model(s) stored in the file.
    bool LoadFromFile(const std::string& filePath, std::vector<std::string>& outModels);
    // Convenience overload: returns first model only (backwards compat).
    bool LoadFromFile(const std::string& filePath, std::string& outModel);

    // File path management
    std::string GetFilePath() const { return m_filePath; }
    void SetFilePath(const std::string& path) { m_filePath = path; }
    bool HasFilePath() const { return !m_filePath.empty(); }

    // Dirty tracking — true when content has changed since last save/load
    bool IsDirty() const { return m_dirty; }

    // Drop-import contract: a dropped file has been copied into this
    // conversation's Workspace folder.  That copy is durable,
    // user-visible on-disk state even though no message was added, so
    // the conversation must persist — otherwise the freshly minted
    // workflow folder (EnsureConversationWorkflow) is orphaned: no JSON
    // is written, the chat never appears in the sidebar, and the
    // DeleteConversation cleanup that removes workflow dirs is
    // unreachable forever.  Marking dirty lets AutoSaveConversation
    // write the JSON and keeps the existing cleanup path in play.
    void NoteWorkspaceSideEffect() { MarkDirty(); }

    // Conversation metadata
    std::string GetTitle() const { return m_title; }
    void SetTitle(const std::string& title) {
        if (title != m_title) {
            m_title = title;
            MarkDirty();
        }
    }
    std::string GetCreatedAt() const { return m_createdAt; }

    // Sidebar organization metadata.  Omitted from legacy conversation
    // files when false, so older builds continue to load the chat body.
    bool IsPinned() const { return m_pinned; }
    void SetPinned(bool pinned) {
        if (pinned != m_pinned) {
            m_pinned = pinned;
            MarkDirty();
        }
    }
    bool IsArchived() const { return m_archived; }
    void SetArchived(bool archived) {
        if (archived != m_archived) {
            m_archived = archived;
            MarkDirty();
        }
    }

    // ── Project association (Projects Phase 1) ───────────────────
    // Optional long-lived project attached to this conversation.  A
    // missing project keeps legacy chat behavior.  Project folders are
    // never deleted when a chat is deleted; they are durable user data.
    bool HasProject() const { return !m_projectId.empty() && !m_projectRoot.empty(); }
    std::string GetProjectId() const { return m_projectId; }
    std::string GetProjectName() const { return m_projectName; }
    std::string GetProjectRoot() const { return m_projectRoot; }
    void SetProject(const std::string& id,
                    const std::string& name,
                    const std::string& root) {
        if (id != m_projectId || name != m_projectName || root != m_projectRoot) {
            m_projectId = id;
            m_projectName = name;
            m_projectRoot = root;
            MarkDirty();
        }
    }
    void ClearProject() {
        if (HasProject() || !m_projectName.empty()) {
            m_projectId.clear();
            m_projectName.clear();
            m_projectRoot.clear();
            MarkDirty();
        }
    }

    // ── Tool execution context (Phase 3) ──────────────────────────
    // Per-conversation working directory for slash-command tools
    // (/cmd, /read, /ls, /grep).  Empty string means "fall back to
    // the app's current directory".  Persisted alongside the
    // conversation so switching chats restores the right context.
    std::string GetToolCwd() const { return m_toolCwd; }
    void        SetToolCwd(const std::string& cwd) {
        if (cwd != m_toolCwd) {
            m_toolCwd = cwd;
            MarkDirty();
        }
    }

    // Per-conversation timeout override for tool execution, in
    // milliseconds.  0 means "use the global default"
    // (kDefaultToolTimeoutMs in tool_context.h).  Kept on ChatHistory
    // so agent-harness conversations can carry their own limits.
    unsigned long GetToolTimeoutMs() const { return m_toolTimeoutMs; }
    void          SetToolTimeoutMs(unsigned long ms) {
        if (ms != m_toolTimeoutMs) {
            m_toolTimeoutMs = ms;
            MarkDirty();
        }
    }

    // Per-conversation reasoning override (/think on|off|auto).
    // Persisted alongside the conversation like the tool CWD so
    // switching chats restores the chosen mode.
    ThinkOverride GetThinkOverride() const { return m_thinkOverride; }
    void          SetThinkOverride(ThinkOverride mode) {
        if (mode != m_thinkOverride) {
            m_thinkOverride = mode;
            MarkDirty();
        }
    }

    // Per-conversation approval memory.  In this polish pass, plain
    // approve enables one-approval mode for this chat; approve once
    // remains available for a single-card approval.  After trust is
    // enabled, subsequent approval-required tools skip the approval
    // card until the conversation is cleared or reloaded.
    //
    // Exception: python_install_package is intentionally excluded from
    // the chat-wide trust flag.  Each install names a distinct package
    // that touches the user's Python environment, so it always renders
    // its own approval card with the exact package name even when
    // one-approval mode is on.  An explicit "approve once" of an
    // install request still individually remembers that single tool
    // name (via RememberToolApproval), but installs cannot be
    // wholesale-approved for the rest of the chat.
    //
    // This flag itself is in-memory only and is never persisted with
    // the conversation file.  However, trust now has app-SESSION
    // lifetime rather than dying on every reload: granting chat-wide
    // trust also records the conversation path in
    // ConversationRegistry (RememberSessionTrust), and
    // ConversationController::LoadConversationFromPath re-arms this
    // flag when a session-trusted conversation is reopened.  Restarting
    // LlamaBoss clears all session grants, so a conversation reopened
    // in a later run always starts with a clean trust state.
    bool IsToolChatApproved(const std::string& name) const {
        if (name == tool_names::kPythonInstallPackage) {
            // Per-package review is the safety boundary now that the
            // package allowlist has been retired.  Never bypass.
            return false;
        }
        return m_chatApprovalTrustEnabled ||
               (!name.empty() && m_chatApprovedTools.count(name) > 0);
    }
    bool IsChatApprovalTrustEnabled() const {
        return m_chatApprovalTrustEnabled;
    }
    void RememberToolApproval(const std::string& name) {
        if (!name.empty()) m_chatApprovedTools.insert(name);
    }
    void RememberAllToolApprovalsForChat() {
        m_chatApprovalTrustEnabled = true;
    }
    void ClearChatApprovedTools() {
        m_chatApprovedTools.clear();
        m_chatApprovalTrustEnabled = false;
    }

    // ── Goals Phase 12: durable mission state + awaiting-user pauses ──
    // Goal state saves with the conversation JSON: objective, status,
    // verifier bookkeeping, continuation budget state, drafted verification
    // contract, and compact structured AgentEvent evidence.  The
    // explicitly-cleared anti-ghosting tombstone remains runtime-only and is
    // intentionally not persisted.
    bool HasGoal() const { return m_goalState.HasGoal(); }
    bool HasActiveGoal() const { return m_goalState.IsActive(); }
    bool HasPausedGoal() const { return m_goalState.IsPaused(); }
    bool HasAwaitingUserGoal() const { return m_goalState.IsAwaitingUser(); }
    bool HasCompletedGoal() const { return m_goalState.IsCompleted(); }
    bool HasBudgetReachedGoal() const { return m_goalState.IsBudgetReached(); }
    bool GoalContractReady() const { return m_goalState.contract.IsReady(); }
    bool GoalContractDrafting() const { return m_goalState.contract.IsDrafting(); }
    const GoalState& GetGoalState() const { return m_goalState; }

    void StartGoal(const std::string& objective) {
        m_goalState.Start(objective);
        MarkDirty();
    }
    bool PauseGoal() {
        if (!m_goalState.HasGoal() || m_goalState.IsPaused()) return false;
        m_goalState.Pause();
        MarkDirty();
        return true;
    }
    bool ResumeGoal() {
        if (!m_goalState.HasGoal() || m_goalState.IsActive()) return false;
        m_goalState.Resume();
        MarkDirty();
        return true;
    }
    void ClearGoal() {
        if (!m_goalState.HasGoal()) return;
        m_goalState.Clear();
        MarkDirty();
    }

    void BeginGoalContractDrafting() {
        if (!m_goalState.HasGoal()) return;
        m_goalState.BeginContractDrafting();
        MarkDirty();
    }
    void SetGoalContractReady(const std::vector<std::string>& successCriteria,
                              const std::vector<std::string>& constraints,
                              const std::vector<std::string>& evidenceChecks,
                              const std::string& builderReason) {
        m_goalState.SetContractReady(successCriteria, constraints, evidenceChecks, builderReason);
        MarkDirty();
    }
    void MarkGoalContractFailed(const std::string& reason) {
        m_goalState.MarkContractFailed(reason);
        MarkDirty();
    }

    void AppendGoalStructuredAgentEvidence(const std::string& chunk) {
        if (!m_goalState.HasGoal()) return;
        m_goalState.AppendStructuredAgentEvidence(chunk);
        MarkDirty();
    }
    const std::vector<std::string>& GetGoalStructuredAgentEvidence() const {
        return m_goalState.structuredAgentEvidence;
    }

    void NoteGoalTurnInterrupted(const std::string& reason) {
        if (!m_goalState.HasGoal()) return;
        m_goalState.MarkInterrupted(reason);
        MarkDirty();
    }

    void MarkGoalAwaitingUser(const std::string& reason,
                              const std::string& promptEvidence) {
        m_goalState.MarkAwaitingUser(reason, promptEvidence);
        MarkDirty();
    }

    void RecordGoalAwaitingUserReply(const std::string& replyEvidence) {
        if (!m_goalState.IsAwaitingUser()) return;
        m_goalState.RecordAwaitingUserReply(replyEvidence);
        MarkDirty();
    }

    void NoteGoalVerifierContinue(const std::string& reason) {
        m_goalState.MarkVerifierContinue(reason);
        MarkDirty();
    }
    void NoteGoalVerifierUnclear(const std::string& reason) {
        m_goalState.MarkVerifierUnclear(reason);
        MarkDirty();
    }
    void MarkGoalVerifiedComplete(const std::string& reason) {
        m_goalState.MarkVerifiedComplete(reason);
        MarkDirty();
    }
    bool CanGoalAutoContinue(int maxContinuations) const {
        return m_goalState.CanAutoContinue(maxContinuations);
    }
    void ConsumeGoalAutoContinuation() {
        if (!m_goalState.IsActive()) return;
        m_goalState.ConsumeAutoContinuation();
        MarkDirty();
    }
    void MarkGoalBudgetReached(const std::string& reason) {
        m_goalState.MarkBudgetReached(reason);
        MarkDirty();
    }

    // Generate a title from the first user message
    std::string GenerateTitle() const;

    // Get the default conversations directory (creates it if needed)
    static std::string GetConversationsDir();
    // Generate a unique filename for a new conversation
    static std::string GenerateFilePath();

    // ── Per-conversation workflow helpers ─────────────────────────
    // User-visible working area for files created/imported during a
    // single conversation.  Conversation JSON stays under
    // %LOCALAPPDATA%\LlamaBoss\conversations; workflow files live
    // under %USERPROFILE%\LlamaBoss\Workflows\chat_xxxxxxxx.
    //
    // This keeps each chat's files together, lets new chats reuse clean
    // filenames, and makes deleting a chat able to delete its files too.
    static std::string GetWorkflowsDir();
    static std::string GetWorkflowDir(const std::string& conversationPath);
    static std::string GetConversationWorkspaceDir(const std::string& conversationPath);
    static bool        EnsureWorkflowDir(const std::string& conversationPath);

    // ── Attachment sidecar helpers (Phase 3) ──────────────────────
    // User-uploaded attachments now live inside the conversation
    // workflow folder instead of one global sidecar area.
    static std::string GetAttachmentDir(const std::string& conversationPath);

    // Relative path prefix stored in message attachment metadata.  This
    // remains relative for history portability, but is now relative to
    // the conversation workflow root.
    static std::string GetAttachmentRelDir(const std::string& conversationPath);

    // ── Generated-files sidecar helpers ───────────────────────────
    // Files generated from assistant code blocks/artifacts.
    static std::string GetGeneratedFilesDir(const std::string& conversationPath);
    static std::string GetGeneratedFilesRelDir(const std::string& conversationPath);

    // ── Tool-result formatting (Phase 3) ──────────────────────────
    // Unified formatter for any tool invocation round-tripped into the
    // conversation history as a user message.  Emits:
    //
    //   [tool: <toolTag>]
    //   > <commandEcho>
    //
    //   ```<bodyLang>
    //   <body>
    //   ```
    //
    //   [error]
    //   ```
    //   <errorBody>
    //   ```
    //
    //   [status: <chip1>, <chip2>, ...]
    //
    // The body fence length is computed as N+1 backticks where N is
    // the longest backtick run in the body — this keeps the fence
    // robust when /read dumps a markdown file or a code sample that
    // itself contains ``` fences.  Error body uses the same rule.
    // Any section whose input string is empty is skipped; an empty
    // body is common for "did nothing useful" commands like
    // `$null = 1+1`.
    static std::string FormatToolBlockAsUserMessage(
        const std::string& toolTag,
        const std::string& commandEcho,
        const std::string& body,
        const std::string& errorBody,
        const std::vector<std::string>& statusChips,
        const std::string& bodyLang = "",
        const std::vector<PresentedFile>& presentedFiles = {});

private:
    std::vector<Poco::JSON::Object::Ptr> m_messages;

    // Tool-result bodies elided by the most recent BuildChatRequestJson
    // call (context meter's "·elided" indicator).  Reset at the start of
    // every build.
    int m_lastBuildElidedCount = 0;

    // Whether the most recent BuildChatRequestJson projected persisted
    // image attachments into a multimodal content array (Phase 1c
    // carrier).  Reset at the start of every build and of every
    // stringify pass, so the value always reflects the FINAL body.
    bool m_lastBuildProjectedImages = false;

    // File persistence state
    std::string m_filePath;     // Current file path (empty = unsaved)
    std::string m_title;        // Conversation title
    std::string m_createdAt;    // ISO timestamp of creation
    std::string m_updatedAt;    // ISO timestamp of last content activity
    bool        m_dirty = false; // True when content changed since last save/load
    std::uint64_t m_revision = 0; // Monotonic mutation generation for async save commits

    void MarkDirty() {
        m_dirty = true;
        ++m_revision;
    }

    // Tool execution context (Phase 3) — persisted per-conversation.
    // Empty / 0 means "use the global default" at resolution time.
    std::string   m_toolCwd;
    unsigned long m_toolTimeoutMs = 0;

    // Per-conversation reasoning override (/think).  Auto keeps the
    // historical request shape (no reasoning fields on the wire).
    ThinkOverride m_thinkOverride = ThinkOverride::Auto;

    // Optional project association (Projects Phase 1).
    std::string m_projectId;
    std::string m_projectName;
    std::string m_projectRoot;

    // Sidebar organization metadata (Phase 4).
    bool m_pinned = false;
    bool m_archived = false;

    // Per-conversation approval memory (in-memory only; cleared on
    // Clear() and on conversation load).  Lives here rather than on
    // the agent or frame so loading a different chat naturally drops
    // the prior session's approval choices.
    bool m_chatApprovalTrustEnabled = false;
    std::unordered_set<std::string> m_chatApprovedTools;

    // Goals Phase 1 state is also in-memory only.  Keeping it on
    // ChatHistory rather than MyFrame prevents one chat's goal from leaking
    // into another chat when the conversation controller swaps histories.
    GoalState m_goalState;

    // Streaming accumulation buffer — avoids O(n²) string concatenation
    // in AppendToLastAssistantMessage by accumulating here instead of
    // repeatedly reading/writing the Poco JSON object per delta.
    //
    // The Poco JSON object's "content" field is the source of truth on disk
    // and on the wire; m_streamBuffer is the source of truth in memory while
    // a response is streaming.  The two are reconciled lazily by
    // FlushStreamBuffer() — called automatically before any reader (Save,
    // BuildChatRequestJson) and on stream completion via
    // UpdateLastAssistantMessage().  Per-delta sync used to be unconditional
    // and made streaming O(n²) in body bytes; now we sync only after enough
    // bytes have accumulated to amortize the cost.
    //
    // m_streamBufferDirty is the byte count buffered since the last sync to
    // the JSON object.  It only ticks under non-const flush paths, so it
    // does not need to be mutable; FlushStreamBuffer() is non-const because
    // Poco::SharedPtr propagates const through operator-> (a const
    // SharedPtr yields a const T*), preventing Object::set() from a const
    // member.  See FlushStreamBuffer() for the matching rationale.
    std::string m_streamBuffer;
    std::size_t m_streamBufferDirty = 0;

    // Helper methods
    Poco::JSON::Object::Ptr CreateMessage(const std::string& role,
                                          const std::string& content,
                                          const std::string& model = "");
    bool IsLastMessageRole(const std::string& role) const;
    static std::string CurrentTimestamp();

    // Sync the in-memory streaming buffer onto the last assistant message's
    // JSON "content" field.  No-op if the buffer is clean or the last
    // message is not an assistant message.  See m_streamBuffer comment for
    // the full lifetime / consistency contract.
    //
    // Not const: Poco::SharedPtr's operator->() const returns a const T*,
    // so calling Object::set() through m_messages.back() requires non-const
    // access even though the vector itself is not modified.  Callers that
    // need to flush from an otherwise-const reader path should drop const
    // on themselves rather than reach for const_cast here.
    void FlushStreamBuffer();
};

